source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybindings.conf


$mod = SUPER


exec-once = waybar
exec-once = nm-applet
exec-once = mako


input {

	kb_layout = fr

}


general {

	gaps_in = 5

	gaps_out = 10

}


decoration {

	rounding = 8

	blur {
		 enabled = true
	}

}
